name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t varsha9611/reactjs-app --build-arg REACT_APP_BASE_URL = '${{secrets.REACT_APP_BASE_URL}}' .
      - name: Publish Image to docker hub
        run: docker push varsha9611/reactjs-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull varsha9611/nodejs-app:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container -e PORT=8000 -e MONGO_URL='mongodb+srv://varsha12:varsha1234@cluster0.qmwlhrv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0' varsha9611/reactjs-app